# Generated by Django 4.2.1 on 2023-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(error_messages={'blank': 'Název ligy musí být vyplněn'}, help_text='Zadejte název ligy', max_length=80, verbose_name='Název ligy')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligy',
                'ordering': ['liga'],
            },
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název Klubu musí být vyplněn'}, help_text='Zadejte název Klubu', max_length=80, verbose_name='Název Klubu')),
                ('zalozeni', models.DateField(blank=True, null=True, verbose_name='Datum založení klubu')),
                ('liga', models.ManyToManyField(to='mat_fotbal.liga')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ['nazev'],
            },
        ),
    ]
