# Generated by Django 4.2.1 on 2023-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='zeme',
            field=models.CharField(default='unknown', error_messages={'blank': 'Název země musí být vyplněn'}, help_text='Zadejte název země odkud Klub pochází', max_length=80, verbose_name='Název Země'),
        ),
    ]
