# Generated by Django 4.2.1 on 2023-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0002_klub_zeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnaje', models.PositiveSmallIntegerField(choices=[(0, 'Liga Mistrů'), (1, 'Evropská Liga'), (2, 'Evropská Konferční Liga'), (3, 'Nekvalifikován')], default=3, verbose_name='Hodnocení')),
            ],
            options={
                'verbose_name': 'Turnaj',
                'verbose_name_plural': 'Turnaje',
                'ordering': ['turnaje'],
            },
        ),
    ]
