# Generated by Django 4.2.1 on 2023-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0003_turnaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='turnaje',
            field=models.ManyToManyField(to='mat_fotbal.turnaments'),
        ),
    ]
