# Generated by Django 4.2.1 on 2023-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0004_klub_turnaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klub',
            name='turnaje',
        ),
        migrations.DeleteModel(
            name='Turnaments',
        ),
        migrations.AddField(
            model_name='klub',
            name='turnaje',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Liga Mistrů'), (1, 'Evropská Liga'), (2, 'Evropská Konferční Liga'), (3, 'Nekvalifikován')], default=3, verbose_name='Hodnocení'),
        ),
    ]
