# Generated by Django 4.2.1 on 2023-05-22 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0006_liga_zalozeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vedouci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno trenéra musí být vyplněno'}, help_text='Zadejte jméno trenéra', max_length=80, verbose_name='Jméno Trenéra')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení trenéra musí být vyplněno'}, help_text='Zadejte příjmení trenéra', max_length=50, verbose_name='Příjmení trenéra')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('biografie', models.TextField(blank=True, verbose_name='Životopis')),
            ],
            options={
                'verbose_name': 'Trenér',
                'verbose_name_plural': 'Trenéři',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.AlterField(
            model_name='liga',
            name='zalozeni',
            field=models.IntegerField(default='1900', help_text='Zadejte rok založení ligy', validators=[django.core.validators.MinValueValidator(1898), django.core.validators.MaxValueValidator(2023)], verbose_name='Rok zalozeni'),
        ),
        migrations.AddField(
            model_name='klub',
            name='trener',
            field=models.ManyToManyField(to='mat_fotbal.vedouci'),
        ),
    ]
