# Generated by Django 4.2.1 on 2023-05-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0007_vedouci_alter_liga_zalozeni_klub_trener'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedouci',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='./media'),
        ),
    ]
