# Generated by Django 4.2.1 on 2023-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_fotbal', '0009_klub_foto_klubu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klub',
            name='foto_klubu',
            field=models.ImageField(blank=True, null=True, upload_to='kluby'),
        ),
    ]
